### ISSUE TITLE
vultr_server_info example is incorrect

### ISSUE THREAD

**Issue by Lvl4Sword** [ngine-io/ansible-collection-vultr#18]
In https://docs.ansible.com/ansible/latest/collections/ngine_io/vultr/vultr_server_info_module.html the provided example:

```yaml
- name: Gather Vultr servers information
  ngine_io.vultr.vultr_server_info:
  register: result
```

results in the following error:

``
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find firewall with FIREWALLGROUPID: 0"}
``

Not sure how to continue or what the fix is here.
